[danmakufactory]
fetch.github = "hihkm/DanmakuFactory"
src.git = "https://github.com/hihkm/DanmakuFactory"

[mpv-handler]
cargo_locks = ["Cargo.lock"]
fetch.github = "akiirui/mpv-handler"
src.github = "akiirui/mpv-handler"

[uosc-danmaku]
fetch.github = "Tony15246/uosc_danmaku"
src.github = "Tony15246/uosc_danmaku"
