# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  danmakufactory = {
    pname = "danmakufactory";
    version = "40fe8916f8528f57a4a1ca245d043d5c4d2566eb";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "40fe8916f8528f57a4a1ca245d043d5c4d2566eb";
      fetchSubmodules = false;
      sha256 = "sha256-fxp0lmvIQU7WRs0IkZHpvG73PkgAdiDMQvrGHWSsSqI=";
    };
    date = "2025-05-18";
  };
  mpv-handler = {
    pname = "mpv-handler";
    version = "v0.3.16";
    src = fetchFromGitHub {
      owner = "akiirui";
      repo = "mpv-handler";
      rev = "v0.3.16";
      fetchSubmodules = false;
      sha256 = "sha256-RpfHUVZmhtneeu8PIfxinYG3/groJPA9QveDSvzU6Zo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./mpv-handler-v0.3.16/Cargo.lock;
      outputHashes = {

      };
    };
  };
  uosc-danmaku = {
    pname = "uosc-danmaku";
    version = "v1.3.1";
    src = fetchFromGitHub {
      owner = "Tony15246";
      repo = "uosc_danmaku";
      rev = "v1.3.1";
      fetchSubmodules = false;
      sha256 = "sha256-m+HubIlELU/COP5rgul7LBPaOEWGz2ms89mF/w3ZWGQ=";
    };
  };
}
