# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}:
{
  algermusicplayer-arm = {
    pname = "algermusicplayer-arm";
    version = "4.9.0";
    src = fetchurl {
      url = "https://github.com/algerkong/AlgerMusicPlayer/releases/download/v4.9.0/AlgerMusicPlayer-4.9.0-linux-arm64.AppImage";
      sha256 = "sha256-Evuh6HQhubA4WrQlVot+BCD2avrqpJaxz/L3+AB7sRc=";
    };
  };
  algermusicplayer-x86 = {
    pname = "algermusicplayer-x86";
    version = "4.9.0";
    src = fetchurl {
      url = "https://github.com/algerkong/AlgerMusicPlayer/releases/download/v4.9.0/AlgerMusicPlayer-4.9.0-linux-x86_64.AppImage";
      sha256 = "sha256-fY8lobsRg2nDENYDY3R81zJ2x0Fr29vJccrelbdggmg=";
    };
  };
  danmakufactory = {
    pname = "danmakufactory";
    version = "v1.70";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "v1.70";
      fetchSubmodules = false;
      sha256 = "sha256-dPgWVJuNOzTc+ocMyGHBb4ExB9P1Wu+uTQ62UejAAfE=";
    };
  };
  danmakufactory-git = {
    pname = "danmakufactory-git";
    version = "e16f1ce4984008c6f6b77947894d1aca0c71226c";
    src = fetchFromGitHub {
      owner = "hihkm";
      repo = "DanmakuFactory";
      rev = "e16f1ce4984008c6f6b77947894d1aca0c71226c";
      fetchSubmodules = true;
      sha256 = "sha256-78mn3NgyPzPVdp6lctgMSVve4edWU0Vcgwncf+fYM1k=";
    };
    date = "2025-07-27";
  };
  lxgw-wenkai-gb = {
    pname = "lxgw-wenkai-gb";
    version = "v1.520";
    src = fetchTarball {
      url = "https://github.com/lxgw/LxgwWenkaiGB/releases/download/v1.520/lxgw-wenkai-gb-v1.520.tar.gz";
      sha256 = "sha256-6dZDzz0PPG18x4DzUH/qzq+1grbNIDP6ZDJA4uAOwxc=";
    };
  };
  mpv-handler = {
    pname = "mpv-handler";
    version = "v0.3.16";
    src = fetchFromGitHub {
      owner = "akiirui";
      repo = "mpv-handler";
      rev = "v0.3.16";
      fetchSubmodules = false;
      sha256 = "sha256-RpfHUVZmhtneeu8PIfxinYG3/groJPA9QveDSvzU6Zo=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./mpv-handler-v0.3.16/Cargo.lock;
      outputHashes = {

      };
    };
  };
  pixes = {
    pname = "pixes";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "wgh136";
      repo = "pixes";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-kmbinF4jCelqDkjxAKxnaO+GrIdX9GBHKqaykpPsCGo=";
    };
    "pubspec.lock" = builtins.readFile ./pixes-v1.1.1/pubspec.lock;
  };
  pixes-git = {
    pname = "pixes-git";
    version = "5dad6910fc77f76b74ce510ed069e7a8ed37a9cf";
    src = fetchFromGitHub {
      owner = "wgh136";
      repo = "pixes";
      rev = "5dad6910fc77f76b74ce510ed069e7a8ed37a9cf";
      fetchSubmodules = false;
      sha256 = "sha256-WNE6UdALHyz0voiZPscBA9yprPA7Ed1lighg0RJK06Q=";
    };
    "pubspec.lock" =
      builtins.readFile ./pixes-git-5dad6910fc77f76b74ce510ed069e7a8ed37a9cf/pubspec.lock;
    date = "2025-08-03";
  };
  splayer-git = {
    pname = "splayer-git";
    version = "bfcd59dacab07fd665e71a311c5fe8c0a3c548a7";
    src = fetchFromGitHub {
      owner = "imsyy";
      repo = "SPlayer";
      rev = "bfcd59dacab07fd665e71a311c5fe8c0a3c548a7";
      fetchSubmodules = false;
      sha256 = "sha256-SpaisGy7Tcaurgyt4kFYifhIeWoAQoufHZ+8zZaFAvk=";
    };
    date = "2025-05-23";
  };
  uosc-danmaku = {
    pname = "uosc-danmaku";
    version = "v1.3.2";
    src = fetchFromGitHub {
      owner = "Tony15246";
      repo = "uosc_danmaku";
      rev = "v1.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-aeqzdL9i5SkfeW3kXSzubw4vfb7clQhV9DQqANFuAnk=";
    };
  };
  uosc-danmaku-git = {
    pname = "uosc-danmaku-git";
    version = "4c5cacd84a45005811572bcfb745c594e8f5d83b";
    src = fetchFromGitHub {
      owner = "Tony15246";
      repo = "uosc_danmaku";
      rev = "4c5cacd84a45005811572bcfb745c594e8f5d83b";
      fetchSubmodules = false;
      sha256 = "sha256-g6Xxtz66xhCCG/t0s2ygP1dYnxD+pIKwMkyswhzbPpU=";
    };
    date = "2025-08-08";
  };
  vulkan-hdr-layer-kwin6 = {
    pname = "vulkan-hdr-layer-kwin6";
    version = "303e0c69e1d33acd95158d92b1fc652fb5b85399";
    src = fetchFromGitHub {
      owner = "Zamundaaa";
      repo = "VK_hdr_layer";
      rev = "303e0c69e1d33acd95158d92b1fc652fb5b85399";
      fetchSubmodules = true;
      sha256 = "sha256-NsC44Ifl/fAHvFqP7NLrVZ71Y+x5mBEkv+r43HN5yn4=";
    };
    date = "2025-07-31";
  };
  zhuque = {
    pname = "zhuque";
    version = "v0.212";
    src = fetchurl {
      url = "https://github.com/TrionesType/zhuque/releases/download/v0.212/ZhuqueFangsong-v0.212.zip";
      sha256 = "sha256-u4tmGnZD0ilqctnRBTCgCUlBnE5Sf7YXg/c8K6GowGI=";
    };
  };
}
