name: Trigger NUR Update

on:
  push:
    branches:
      - main

concurrency:
  group: update-sources
  cancel-in-progress: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    name: Trigger NUR Update
    steps:
      - name: Trigger NUR update
        run: curl -XPOST "https://nur-update.nix-community.org/update?repo=ccicnce113424"
